/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (EarthwormJim2)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80010E0Cu
#define func_80010E0C BootEntry  /* alias */
